### ISSUE TITLE
Improve navigation usability of official documentation

### ISSUE THREAD

**Issue by alexprut** [ninenines/ninenines.github.io#11]
Hello,
It would be nice to have a _read next_ or _previous_ link at the end in the official documentation of (Cowboy, Ranch, ...) at the end of the pages.

e.g.
![nine nines request documentation](https://cloud.githubusercontent.com/assets/1648497/17439338/d434e290-5b27-11e6-8c42-6f1bd951dbc6.png)

I find it frustrating to go back and change pages, but hey, it's just a thought and small improvement, in any case thanks for everything ;)

**Comment by essen** [comment]
Yeah I know. I'll try to improve docs usability once we get closer to Cowboy 2.0. Thanks for the feedback!

**Comment by essen** [comment]
This is done. For example http://ninenines.eu/docs/en/cowboy/2.0/guide/modern_web/

This won't appear on the Cowboy 1.0 user guide though.

Thanks!
