### ISSUE TITLE
websocket handler init example returns {stop, Req, State}

### ISSUE THREAD

**Issue by shamis** [ninenines/ninenines.github.io#12]
In the [subprotocol section](https://github.com/ninenines/ninenines.github.io/blob/35bc482f0be143abd728a228e937984dc5f6cc73/docs/en/cowboy/2.0/guide/ws_handlers.asciidoc) the init is returning `{stop, Req, State}`. I think this is not a valid return value as only `ok` and handler module name can be returned as the first element in the tuple.

**Comment by essen** [comment]
Good find! It should return `ok` and probably also send a reply back.

**Comment by essen** [comment]
Done locally, updated soon. Thanks!
