### ISSUE TITLE
rate_limited is after forbidden

### ISSUE THREAD

**Issue by helloyan** [ninenines/ninenines.github.io#20]
In the source code, `rate_limited/2` comes after `forbidden/2` instead of `valid_entity_length/2` in the image.

![image](https://github.com/ninenines/ninenines.github.io/assets/1699033/9d314d5c-9494-47e9-8f2f-5b5b422cce54)

**Comment by essen** [comment]
Please open this ticket in https://github.com/ninenines/cowboy

**Comment by helloyan** [comment]
"I believe this is a documentation error rather than a coding error."

**Comment by essen** [comment]
Yes but the documentation is in the Cowboy repository.
